# Generated by Django 4.1.6 on 2023-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('typeOfWord', models.CharField(choices=[('n', 'noun'), ('v', 'verb'), ('adj', 'adjective'), ('adv', 'adverb'), ('prep', 'preposition')], max_length=30)),
                ('meaning', models.CharField(max_length=255)),
                ('example', models.CharField(blank=True, max_length=255)),
                ('synonym', models.ManyToManyField(blank=True, to='lexical.vocabulary')),
            ],
        ),
    ]
