# Generated by Django 4.1.6 on 2023-02-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexicalCategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='example',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='synonym',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='typeOfWord',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(blank=True, max_length=255, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexical.entries')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexical.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(blank=True, max_length=255, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexical.entries')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexical.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='entries',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexical.vocabulary'),
        ),
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexical.entries')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexical.vocabulary')),
            ],
        ),
    ]
