# Generated by Django 4.1.6 on 2023-02-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexical', '0002_entries_remove_vocabulary_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='lexicalCategory',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
    ]
