# Generated by Django 4.1.6 on 2023-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexical', '0004_alter_definitions_entry_alter_examples_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=255, verbose_name='Own Dictionary')),
                ('word', models.ManyToManyField(to='lexical.vocabulary')),
            ],
        ),
    ]
